-----------------
-- COMPANY
-----------------
DROP TABLE COMPANY CASCADE CONSTRAINTS;
CREATE TABLE COMPANY (
	COMP_NO	NUMBER		PRIMARY KEY,
	COMP_NAME	VARCHAR2(100)		NOT NULL,
	COMP_ADDRESS	VARCHAR2(500)		NOT NULL,
    DELETE_YN	CHAR(1)	DEFAULT 'Y' CHECK(DELETE_YN IN ('Y', 'N'))
);
DROP SEQUENCE SEQ_COMPANY_NO;
CREATE SEQUENCE SEQ_COMPANY_NO NOCACHE NOCYCLE;

-----------------
-- DEPT
-----------------
DROP TABLE DEPT CASCADE CONSTRAINTS;
CREATE TABLE DEPT (
	DEPT_NO	NUMBER		PRIMARY KEY,
    COMPANY_NO	NUMBER		NOT NULL,
	DEPT_NAME	VARCHAR2(100)		NULL,
	DELETE_YN	CHAR(1)	DEFAULT 'Y' CHECK(DELETE_YN IN ('Y', 'N')),
    CONSTRAINT FK_COMPANY_DEPT FOREIGN KEY(COMPANY_NO) REFERENCES COMPANY(COMP_NO)
);

DROP SEQUENCE SEQ_DEPT_NO;
CREATE SEQUENCE SEQ_DEPT_NO NOCACHE NOCYCLE;

-----------------
-- RANK
-----------------
DROP TABLE RANK CASCADE CONSTRAINTS;
CREATE TABLE RANK (
	RANK_NO	NUMBER		PRIMARY KEY,
	RANK_NAME	VARCHAR2(100)		NULL,
	DELETE_YN	CHAR(1)	DEFAULT 'Y' CHECK(DELETE_YN IN ('Y', 'N'))
);
DROP SEQUENCE SEQ_RANK_NO;
CREATE SEQUENCE SEQ_RANK_NO NOCACHE NOCYCLE;

-----------------
-- EMPLOYEE
-----------------
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
CREATE TABLE EMPLOYEE (
	EMP_NO	NUMBER		PRIMARY KEY,
	ID	VARCHAR2(50)		NOT NULL,
	PWD	VARCHAR2(100)		NOT NULL,
	NICK	VARCHAR2(50)		NOT NULL,
	PHONE	VARCHAR2(50)		NOT NULL,
	EMAIL	VARCHAR2(100)		NULL,
	ADDRESS	VARCHAR2(100)		NULL,
	SS_NO	CHAR(13)		NOT NULL,
	HIRE_DATE	TIMESTAMP		NULL,
  QUIT_DATE   TIMESTAMP		NULL,
	SALARY	NUMBER		NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N')),
	PROFILE_PATH	VARCHAR2(1000)		NULL,
	COMPANY_NO	NUMBER		NOT NULL,
	DEPT_NO	NUMBER		NOT NULL,
	RANK_NO	NUMBER		NOT NULL,
    CONSTRAINT FK_COMPANY_MEMBER FOREIGN KEY(COMPANY_NO) REFERENCES COMPANY(COMP_NO),
    CONSTRAINT FK_DEPT_MEMBER FOREIGN KEY(DEPT_NO) REFERENCES DEPT(DEPT_NO),
    CONSTRAINT FK_RANK_MEMBER FOREIGN KEY(RANK_NO) REFERENCES RANK(RANK_NO)
);
DROP SEQUENCE SEQ_EMPLOYEE_NO;
CREATE SEQUENCE SEQ_EMPLOYEE_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_EMPLOYEE_NO;
CREATE SEQUENCE SEQ_EMPLOYEE_NO NOCACHE NOCYCLE;

--------------------------------------------
---- NOTICE 공지게시판 --------
--------------------------------------------
DROP TABLE NOTICE_BOARD CASCADE CONSTRAINTS;
CREATE TABLE NOTICE_BOARD (
	BOARD_NO	    NUMBER		        PRIMARY KEY,
	TITLE	        VARCHAR2(100)		NOT NULL,
	CONTENT	        VARCHAR2(4000)		NOT NULL,
    WRITER	        NUMBER		        NOT NULL,
    CNT         	NUMBER	            DEFAULT 0,
	ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE,
	MODIFY_DATE	    TIMESTAMP		    DEFAULT SYSDATE,
	STATUS	        CHAR(1)	            DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N')),
    REPLY_COUNT     NUMBER	            DEFAULT 0, -- 추가함 // 댓글 수
	CONSTRAINT      FK_NOTICE_BOARD     FOREIGN KEY(WRITER)     REFERENCES   EMPLOYEE(EMP_NO) 
);
DROP SEQUENCE SEQ_NOTICE_BOARD_NO;
CREATE SEQUENCE SEQ_NOTICE_BOARD_NO NOCACHE NOCYCLE;

--------------------------------------------
-- NOTICE REPLY 공지_댓글
--------------------------------------------
DROP TABLE NOTICE_REPLY CASCADE CONSTRAINTS;
CREATE TABLE NOTICE_REPLY(
      REPLY_NO      NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , BNO           NUMBER          NOT NULL            --  참조하는 게시글 번호
    , WRITER        NUMBER          NOT NULL            --  댓글 작성자
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE	TIMESTAMP		DEFAULT SYSDATE
    , STATUS	    CHAR(1)	        DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N'))
    , CONSTRAINT FK_NOTICE_REPLY_BOARD FOREIGN KEY(BNO) REFERENCES NOTICE_BOARD(BOARD_NO) on delete cascade
    , CONSTRAINT FK_NOTICE_REPLY_MEMBER FOREIGN KEY(WRITER) REFERENCES EMPLOYEE(EMP_NO) on delete cascade
);

DROP SEQUENCE SEQ_NOTICE_REPLY_NO;
CREATE SEQUENCE SEQ_NOTICE_REPLY_NO NOCACHE NOCYCLE;

--------------------------------------------
----------INSERT문(NOTICE_BOARD)
--------------------------------------------
INSERT INTO NOTICE_BOARD(BOARD_NO, TITLE, CONTENT, WRITER) VALUES (SEQ_NOTICE_BOARD_NO.NEXTVAL, '제목!!', '내용~!', 1);

--------------------------------------------
---- CLOUD 자료실 게시판 --------
--------------------------------------------
DROP TABLE CLOUD_BOARD CASCADE CONSTRAINTS;
CREATE TABLE CLOUD_BOARD (
	BOARD_NO	    NUMBER		        PRIMARY KEY,
	TITLE	        VARCHAR2(100)		NOT NULL,
	CONTENT	        VARCHAR2(4000)		NOT NULL,
    WRITER	        NUMBER		        NOT NULL,
    CNT         	NUMBER	            DEFAULT 0,
    PROFILE_PATH	VARCHAR2(1000)		NULL,  
	ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE,
	MODIFY_DATE	    TIMESTAMP		    DEFAULT SYSDATE,
	STATUS	        CHAR(1)	            DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N')),
	CONSTRAINT      FK_CLOUD_BOARD     FOREIGN KEY(WRITER)     REFERENCES   EMPLOYEE(EMP_NO)
);
DROP SEQUENCE SEQ_CLOUD_BOARD_NO;
CREATE SEQUENCE SEQ_CLOUD_BOARD_NO NOCACHE NOCYCLE;


--------------------------------------------
---- FREE 자유게시판 --------
--------------------------------------------
DROP TABLE FREE_BOARD CASCADE CONSTRAINTS;
CREATE TABLE FREE_BOARD (
	BOARD_NO	    NUMBER		        PRIMARY KEY,
	TITLE	        VARCHAR2(100)		NOT NULL,
	CONTENT	        VARCHAR2(4000)		NOT NULL,
    WRITER	        NUMBER		        NOT NULL,
    CNT         	NUMBER	            DEFAULT 0,
	ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE,
	MODIFY_DATE	    TIMESTAMP		    DEFAULT SYSDATE,
	STATUS	        CHAR(1)	            DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N')),
	CONSTRAINT      FK_FREE_BOARD     FOREIGN KEY(WRITER)     REFERENCES   EMPLOYEE(EMP_NO)
);
DROP SEQUENCE SEQ_FREE_BOARD_NO;
CREATE SEQUENCE SEQ_FREE_BOARD_NO NOCACHE NOCYCLE;

--------------------------------------------
-- FREE REPLY 자유_댓글
--------------------------------------------
DROP TABLE FREE_REPLY CASCADE CONSTRAINTS;
CREATE TABLE FREE_REPLY(
      REPLY_NO      NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , BNO           NUMBER          NOT NULL            --  참조하는 게시글 번호
    , WRITER        NUMBER          NOT NULL            --  댓글 작성자
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE	TIMESTAMP		DEFAULT SYSDATE
    , STATUS	    CHAR(1)	        DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N'))
    , CONSTRAINT FK_FREE_REPLY_BOARD FOREIGN KEY(BNO) REFERENCES FREE_BOARD(BOARD_NO)     
    , CONSTRAINT FK_FREE_REPLY_MEMBER FOREIGN KEY(WRITER) REFERENCES EMPLOYEE(EMP_NO)   
);

DROP SEQUENCE SEQ_FREE_REPLY_NO;
CREATE SEQUENCE SEQ_FREE_REPLY_NO NOCACHE NOCYCLE;


--------------------------------------------
---- BLIND 블라인드 게시판 --------
--------------------------------------------
DROP TABLE BLIND_BOARD CASCADE CONSTRAINTS;
CREATE TABLE BLIND_BOARD (
	BOARD_NO	    NUMBER		        PRIMARY KEY,
	TITLE	        VARCHAR2(100)		NOT NULL,
	CONTENT	        VARCHAR2(4000)		NOT NULL,
    WRITER	        NUMBER		        NOT NULL,
    CNT         	NUMBER	            DEFAULT 0,
	ENROLL_DATE	    TIMESTAMP	        DEFAULT SYSDATE,
	MODIFY_DATE	    TIMESTAMP		    DEFAULT SYSDATE,
	STATUS	        CHAR(1)	            DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N')),
	CONSTRAINT      FK_BLIND_BOARD     FOREIGN KEY(WRITER)     REFERENCES   EMPLOYEE(EMP_NO)
);
DROP SEQUENCE SEQ_BLIND_BOARD_NO;
CREATE SEQUENCE SEQ_BLIND_BOARD_NO NOCACHE NOCYCLE;

--------------------------------------------
-- BLIND REPLY 블라인드_댓글
--------------------------------------------
DROP TABLE BLIND_REPLY CASCADE CONSTRAINTS;
CREATE TABLE BLIND_REPLY(
      REPLY_NO      NUMBER          PRIMARY KEY
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , BNO           NUMBER          NOT NULL           
    , WRITER        NUMBER          NOT NULL           
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE	TIMESTAMP		DEFAULT SYSDATE
    , STATUS	    CHAR(1)	        DEFAULT 'Y' CHECK(STATUS IN ('Y', 'N'))
    , CONSTRAINT FK_BLIND_REPLY_BOARD FOREIGN KEY(BNO) REFERENCES BLIND_BOARD(BOARD_NO)     
    , CONSTRAINT FK_BLIND_REPLY_MEMBER FOREIGN KEY(WRITER) REFERENCES EMPLOYEE(EMP_NO)   
);

DROP SEQUENCE SEQ_BLIND_REPLY_NO;
CREATE SEQUENCE SEQ_BLIND_REPLY_NO NOCACHE NOCYCLE;

--------------------------------------------
-- NOTICE 공지게시판(스크랩)
--------------------------------------------
DROP TABLE NOTICE_SCRAP CASCADE CONSTRAINTS;
CREATE TABLE NOTICE_SCRAP(
    SCRAP_NO NUMBER PRIMARY KEY,
    EMP_NO   NUMBER		NOT NULL,       -- 스크랩 한 회원 번호
    BNO     NUMBER   NOT NULL,           --  참조하는 게시글 번호
    SCRAP_DATE TIMESTAMP DEFAULT SYSDATE,   
    CONSTRAINT  FK_NOTICE_SCRAP_EMP FOREIGN KEY(EMP_NO)  REFERENCES  EMPLOYEE(EMP_NO) on delete cascade,
    CONSTRAINT FK_NOTICE_SCRAP_BOARD FOREIGN KEY(BNO) REFERENCES NOTICE_BOARD(BOARD_NO)  on delete cascade
    
);

DROP SEQUENCE SEQ_NOTICE_SCRAP_NO;
CREATE SEQUENCE SEQ_NOTICE_SCRAP_NO NOCACHE NOCYCLE;

COMMIT;
